name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ajuste para a versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test  # Ajuste se o comando para rodar os testes for diferente

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/results  # Ajuste para o caminho onde seus resultados são armazenados
